// カテゴリ別 文づくりデータ
const SENTENCE_DATA = {
  colors: {
    reorder: [
      { parts: ["I", "like", "red", "."], answer: "I like red." },
      { parts: ["My", "favorite", "color", "is", "blue", "."], answer: "My favorite color is blue." },
      { parts: ["The", "sky", "is", "blue", "."], answer: "The sky is blue." },
      { parts: ["I", "like", "pink", "and", "purple", "."], answer: "I like pink and purple." },
      { parts: ["What", "color", "do", "you", "like", "?"], answer: "What color do you like?" },
      { parts: ["This", "flower", "is", "yellow", "."], answer: "This flower is yellow." },
    ],
    choose: [
      { emoji: "🔴", ja: "赤がすき", correct: "I like red.", wrongs: ["I like blue.", "I have a pen."] },
      { emoji: "🔵", ja: "空は青い", correct: "The sky is blue.", wrongs: ["The sky is red.", "I like dogs."] },
      { emoji: "🟢", ja: "緑がすき", correct: "I like green.", wrongs: ["I like soup.", "This is my school."] },
      { emoji: "🟡", ja: "この花は黄色", correct: "This flower is yellow.", wrongs: ["This flower is white.", "I play soccer."] },
      { emoji: "🩷", ja: "ピンクが好きな色", correct: "My favorite color is pink.", wrongs: ["My favorite color is black.", "I have a cat."] },
      { emoji: "🟠", ja: "オレンジがすき", correct: "I like orange.", wrongs: ["I like Monday.", "This is my bag."] },
    ],
    fillblank: [
      { sentence: "I like ___.", answer: "red", choices: ["red", "dog", "milk", "Monday"] },
      { sentence: "The sky is ___.", answer: "blue", choices: ["blue", "cake", "fish", "ten"] },
      { sentence: "My favorite color is ___.", answer: "green", choices: ["green", "soccer", "egg", "father"] },
      { sentence: "This flower is ___.", answer: "yellow", choices: ["yellow", "book", "bear", "five"] },
      { sentence: "I like ___ and purple.", answer: "pink", choices: ["pink", "rice", "horse", "ear"] },
      { sentence: "The cat is ___.", answer: "black", choices: ["black", "apple", "Sunday", "hand"] },
    ],
  },
  numbers: {
    reorder: [
      { parts: ["I", "am", "ten", "years", "old", "."], answer: "I am ten years old." },
      { parts: ["I", "have", "two", "cats", "."], answer: "I have two cats." },
      { parts: ["There", "are", "five", "apples", "."], answer: "There are five apples." },
      { parts: ["How", "old", "are", "you", "?"], answer: "How old are you?" },
      { parts: ["I", "have", "three", "brothers", "."], answer: "I have three brothers." },
      { parts: ["There", "are", "seven", "days", "."], answer: "There are seven days." },
    ],
    choose: [
      { emoji: "🔟", ja: "10さいです", correct: "I am ten years old.", wrongs: ["I am five years old.", "I like red."] },
      { emoji: "2️⃣", ja: "猫が2ひき", correct: "I have two cats.", wrongs: ["I have two dogs.", "I like soccer."] },
      { emoji: "5️⃣", ja: "りんごが5つ", correct: "There are five apples.", wrongs: ["There are five cats.", "I am five."] },
      { emoji: "3️⃣", ja: "兄弟が3人", correct: "I have three brothers.", wrongs: ["I have three pens.", "This is my school."] },
      { emoji: "7️⃣", ja: "7日ある", correct: "There are seven days.", wrongs: ["There are seven cats.", "I like seven."] },
      { emoji: "4️⃣", ja: "本が4冊", correct: "I have four books.", wrongs: ["I have four mothers.", "It is four."] },
    ],
    fillblank: [
      { sentence: "I am ___ years old.", answer: "ten", choices: ["ten", "red", "dog", "Monday"] },
      { sentence: "I have ___ cats.", answer: "two", choices: ["two", "blue", "milk", "hand"] },
      { sentence: "There are ___ apples.", answer: "five", choices: ["five", "soccer", "bread", "ear"] },
      { sentence: "I have ___ brothers.", answer: "three", choices: ["three", "green", "cake", "nose"] },
      { sentence: "There are ___ days in a week.", answer: "seven", choices: ["seven", "fish", "chair", "Sunday"] },
      { sentence: "I have ___ pencils.", answer: "four", choices: ["four", "orange", "bear", "sister"] },
    ],
  },
  animals: {
    reorder: [
      { parts: ["I", "like", "dogs", "."], answer: "I like dogs." },
      { parts: ["I", "have", "a", "cat", "."], answer: "I have a cat." },
      { parts: ["Do", "you", "like", "rabbits", "?"], answer: "Do you like rabbits?" },
      { parts: ["This", "is", "a", "big", "elephant", "."], answer: "This is a big elephant." },
      { parts: ["I", "can", "see", "a", "bird", "."], answer: "I can see a bird." },
      { parts: ["Lions", "are", "strong", "."], answer: "Lions are strong." },
    ],
    choose: [
      { emoji: "🐕", ja: "犬がすき", correct: "I like dogs.", wrongs: ["I like cats.", "I have a pen."] },
      { emoji: "🐈", ja: "猫をかっている", correct: "I have a cat.", wrongs: ["I have a dog.", "I like red."] },
      { emoji: "🐘", ja: "大きいぞう", correct: "This is a big elephant.", wrongs: ["This is a big cat.", "I play tennis."] },
      { emoji: "🐦", ja: "鳥が見える", correct: "I can see a bird.", wrongs: ["I can see a fish.", "I like cake."] },
      { emoji: "🦁", ja: "ライオンは強い", correct: "Lions are strong.", wrongs: ["Lions are small.", "I like blue."] },
      { emoji: "🐰", ja: "うさぎがすき？", correct: "Do you like rabbits?", wrongs: ["Do you like snakes?", "I am ten."] },
    ],
    fillblank: [
      { sentence: "I like ___.", answer: "dogs", choices: ["dogs", "red", "cake", "Monday"] },
      { sentence: "I have a ___.", answer: "cat", choices: ["cat", "soccer", "bread", "hand"] },
      { sentence: "This is a big ___.", answer: "elephant", choices: ["elephant", "pencil", "blue", "father"] },
      { sentence: "I can see a ___.", answer: "bird", choices: ["bird", "milk", "green", "desk"] },
      { sentence: "___ are strong.", answer: "Lions", choices: ["Lions", "Books", "Eggs", "Colors"] },
      { sentence: "Do you like ___?", answer: "rabbits", choices: ["rabbits", "chairs", "soup", "Tuesday"] },
    ],
  },
  food: {
    reorder: [
      { parts: ["I", "like", "rice", "."], answer: "I like rice." },
      { parts: ["I", "want", "pizza", "."], answer: "I want pizza." },
      { parts: ["Do", "you", "like", "cheese", "?"], answer: "Do you like cheese?" },
      { parts: ["I", "eat", "bread", "every", "morning", "."], answer: "I eat bread every morning." },
      { parts: ["This", "cake", "is", "good", "."], answer: "This cake is good." },
      { parts: ["I", "drink", "milk", "every", "day", "."], answer: "I drink milk every day." },
    ],
    choose: [
      { emoji: "🍚", ja: "ごはんがすき", correct: "I like rice.", wrongs: ["I like pizza.", "I have a dog."] },
      { emoji: "🍕", ja: "ピザがほしい", correct: "I want pizza.", wrongs: ["I want a cat.", "I like blue."] },
      { emoji: "🎂", ja: "このケーキはおいしい", correct: "This cake is good.", wrongs: ["This cake is bad.", "I play soccer."] },
      { emoji: "🥛", ja: "毎日牛乳を飲む", correct: "I drink milk every day.", wrongs: ["I drink soup every day.", "I like red."] },
      { emoji: "🍞", ja: "毎朝パンを食べる", correct: "I eat bread every morning.", wrongs: ["I eat rice every morning.", "I am ten."] },
      { emoji: "🧀", ja: "チーズがすき？", correct: "Do you like cheese?", wrongs: ["Do you like snakes?", "This is my school."] },
    ],
    fillblank: [
      { sentence: "I like ___.", answer: "rice", choices: ["rice", "dog", "blue", "Monday"] },
      { sentence: "I want ___.", answer: "pizza", choices: ["pizza", "bear", "green", "hand"] },
      { sentence: "This ___ is good.", answer: "cake", choices: ["cake", "bird", "red", "desk"] },
      { sentence: "I drink ___ every day.", answer: "milk", choices: ["milk", "lion", "yellow", "Sunday"] },
      { sentence: "I eat ___ every morning.", answer: "bread", choices: ["bread", "cat", "pink", "ear"] },
      { sentence: "Do you like ___?", answer: "cheese", choices: ["cheese", "horse", "purple", "leg"] },
    ],
  },
  fruits: {
    reorder: [
      { parts: ["I", "like", "apples", "."], answer: "I like apples." },
      { parts: ["This", "is", "a", "banana", "."], answer: "This is a banana." },
      { parts: ["Do", "you", "like", "strawberries", "?"], answer: "Do you like strawberries?" },
      { parts: ["I", "eat", "oranges", "every", "day", "."], answer: "I eat oranges every day." },
      { parts: ["Watermelons", "are", "big", "."], answer: "Watermelons are big." },
      { parts: ["I", "want", "a", "peach", "."], answer: "I want a peach." },
    ],
    choose: [
      { emoji: "🍎", ja: "りんごがすき", correct: "I like apples.", wrongs: ["I like bananas.", "I have a pen."] },
      { emoji: "🍌", ja: "これはバナナ", correct: "This is a banana.", wrongs: ["This is an orange.", "I like dogs."] },
      { emoji: "🍓", ja: "いちごがすき？", correct: "Do you like strawberries?", wrongs: ["Do you like lemons?", "I am ten."] },
      { emoji: "🍉", ja: "すいかは大きい", correct: "Watermelons are big.", wrongs: ["Watermelons are small.", "I play soccer."] },
      { emoji: "🍑", ja: "桃がほしい", correct: "I want a peach.", wrongs: ["I want a lemon.", "This is my school."] },
      { emoji: "🍊", ja: "毎日オレンジを食べる", correct: "I eat oranges every day.", wrongs: ["I eat grapes every day.", "I like blue."] },
    ],
    fillblank: [
      { sentence: "I like ___.", answer: "apples", choices: ["apples", "dogs", "red", "Monday"] },
      { sentence: "This is a ___.", answer: "banana", choices: ["banana", "pencil", "blue", "father"] },
      { sentence: "Do you like ___?", answer: "strawberries", choices: ["strawberries", "chairs", "green", "ear"] },
      { sentence: "___ are big.", answer: "Watermelons", choices: ["Watermelons", "Pens", "Eyes", "Colors"] },
      { sentence: "I want a ___.", answer: "peach", choices: ["peach", "desk", "black", "brother"] },
      { sentence: "I eat ___ every day.", answer: "oranges", choices: ["oranges", "bears", "white", "Thursday"] },
    ],
  },
  body: {
    reorder: [
      { parts: ["This", "is", "my", "hand", "."], answer: "This is my hand." },
      { parts: ["I", "have", "two", "eyes", "."], answer: "I have two eyes." },
      { parts: ["Touch", "your", "nose", "."], answer: "Touch your nose." },
      { parts: ["Wash", "your", "hands", "."], answer: "Wash your hands." },
      { parts: ["I", "have", "two", "ears", "."], answer: "I have two ears." },
      { parts: ["Open", "your", "mouth", "."], answer: "Open your mouth." },
    ],
    choose: [
      { emoji: "✋", ja: "これは私の手", correct: "This is my hand.", wrongs: ["This is my foot.", "I like red."] },
      { emoji: "👁️", ja: "目が2つある", correct: "I have two eyes.", wrongs: ["I have two noses.", "I play soccer."] },
      { emoji: "👃", ja: "鼻をさわって", correct: "Touch your nose.", wrongs: ["Touch your ear.", "I like cake."] },
      { emoji: "✋", ja: "手を洗って", correct: "Wash your hands.", wrongs: ["Wash your feet.", "I am ten."] },
      { emoji: "👄", ja: "口を開けて", correct: "Open your mouth.", wrongs: ["Open your eyes.", "This is my school."] },
      { emoji: "👂", ja: "耳が2つある", correct: "I have two ears.", wrongs: ["I have two mouths.", "I like dogs."] },
    ],
    fillblank: [
      { sentence: "This is my ___.", answer: "hand", choices: ["hand", "dog", "red", "Monday"] },
      { sentence: "I have two ___.", answer: "eyes", choices: ["eyes", "cakes", "blues", "schools"] },
      { sentence: "Touch your ___.", answer: "nose", choices: ["nose", "book", "green", "soccer"] },
      { sentence: "Wash your ___.", answer: "hands", choices: ["hands", "cats", "yellow", "Sunday"] },
      { sentence: "Open your ___.", answer: "mouth", choices: ["mouth", "desk", "pink", "father"] },
      { sentence: "I have two ___.", answer: "ears", choices: ["ears", "pens", "brown", "Friday"] },
    ],
  },
  school: {
    reorder: [
      { parts: ["This", "is", "my", "school", "."], answer: "This is my school." },
      { parts: ["I", "have", "a", "pencil", "."], answer: "I have a pencil." },
      { parts: ["Where", "is", "my", "bag", "?"], answer: "Where is my bag?" },
      { parts: ["I", "like", "my", "teacher", "."], answer: "I like my teacher." },
      { parts: ["Open", "your", "notebook", "."], answer: "Open your notebook." },
      { parts: ["I", "go", "to", "school", "every", "day", "."], answer: "I go to school every day." },
    ],
    choose: [
      { emoji: "🏫", ja: "これは私の学校", correct: "This is my school.", wrongs: ["This is my house.", "I like dogs."] },
      { emoji: "✏️", ja: "えんぴつを持っている", correct: "I have a pencil.", wrongs: ["I have a cat.", "I like blue."] },
      { emoji: "🎒", ja: "かばんはどこ？", correct: "Where is my bag?", wrongs: ["Where is my cat?", "I am ten."] },
      { emoji: "👩‍🏫", ja: "先生がすき", correct: "I like my teacher.", wrongs: ["I like my dog.", "This is red."] },
      { emoji: "📓", ja: "ノートを開けて", correct: "Open your notebook.", wrongs: ["Open your bag.", "I play soccer."] },
      { emoji: "🏫", ja: "毎日学校に行く", correct: "I go to school every day.", wrongs: ["I go to the park every day.", "I like cake."] },
    ],
    fillblank: [
      { sentence: "This is my ___.", answer: "school", choices: ["school", "dog", "red", "Monday"] },
      { sentence: "I have a ___.", answer: "pencil", choices: ["pencil", "lion", "blue", "mother"] },
      { sentence: "Where is my ___?", answer: "bag", choices: ["bag", "bear", "green", "Sunday"] },
      { sentence: "I like my ___.", answer: "teacher", choices: ["teacher", "apple", "pink", "eight"] },
      { sentence: "Open your ___.", answer: "notebook", choices: ["notebook", "horse", "white", "Friday"] },
      { sentence: "I go to ___ every day.", answer: "school", choices: ["school", "fish", "brown", "baby"] },
    ],
  },
  sports: {
    reorder: [
      { parts: ["I", "like", "soccer", "."], answer: "I like soccer." },
      { parts: ["I", "play", "baseball", "."], answer: "I play baseball." },
      { parts: ["Can", "you", "swim", "?"], answer: "Can you swim?" },
      { parts: ["I", "play", "basketball", "after", "school", "."], answer: "I play basketball after school." },
      { parts: ["Let's", "play", "tennis", "."], answer: "Let's play tennis." },
      { parts: ["I", "like", "running", "."], answer: "I like running." },
    ],
    choose: [
      { emoji: "⚽", ja: "サッカーがすき", correct: "I like soccer.", wrongs: ["I like baseball.", "I have a cat."] },
      { emoji: "⚾", ja: "野球をする", correct: "I play baseball.", wrongs: ["I play tennis.", "I like red."] },
      { emoji: "🏊", ja: "泳げる？", correct: "Can you swim?", wrongs: ["Can you run?", "This is my school."] },
      { emoji: "🏀", ja: "放課後バスケをする", correct: "I play basketball after school.", wrongs: ["I play volleyball after school.", "I like cake."] },
      { emoji: "🎾", ja: "テニスをしよう", correct: "Let's play tennis.", wrongs: ["Let's play soccer.", "I am ten."] },
      { emoji: "🏃", ja: "走るのがすき", correct: "I like running.", wrongs: ["I like swimming.", "I have a dog."] },
    ],
    fillblank: [
      { sentence: "I like ___.", answer: "soccer", choices: ["soccer", "red", "milk", "Monday"] },
      { sentence: "I play ___.", answer: "baseball", choices: ["baseball", "cat", "blue", "hand"] },
      { sentence: "Can you ___?", answer: "swim", choices: ["swim", "eat", "blue", "school"] },
      { sentence: "I play ___ after school.", answer: "basketball", choices: ["basketball", "pencil", "green", "mother"] },
      { sentence: "Let's play ___.", answer: "tennis", choices: ["tennis", "book", "pink", "father"] },
      { sentence: "I like ___.", answer: "running", choices: ["running", "bread", "brown", "Sunday"] },
    ],
  },
  days: {
    reorder: [
      { parts: ["Today", "is", "Monday", "."], answer: "Today is Monday." },
      { parts: ["I", "have", "English", "on", "Friday", "."], answer: "I have English on Friday." },
      { parts: ["What", "day", "is", "it", "today", "?"], answer: "What day is it today?" },
      { parts: ["I", "like", "Saturday", "."], answer: "I like Saturday." },
      { parts: ["Sunday", "is", "my", "favorite", "day", "."], answer: "Sunday is my favorite day." },
      { parts: ["We", "have", "P.E.", "on", "Wednesday", "."], answer: "We have P.E. on Wednesday." },
    ],
    choose: [
      { emoji: "🌙", ja: "今日は月曜日", correct: "Today is Monday.", wrongs: ["Today is Friday.", "I like dogs."] },
      { emoji: "✨", ja: "金曜日に英語がある", correct: "I have English on Friday.", wrongs: ["I have English on Monday.", "I like cake."] },
      { emoji: "📅", ja: "今日は何曜日？", correct: "What day is it today?", wrongs: ["What color do you like?", "I am ten."] },
      { emoji: "🌍", ja: "土曜日がすき", correct: "I like Saturday.", wrongs: ["I like Wednesday.", "This is my school."] },
      { emoji: "☀️", ja: "日曜日がいちばんすき", correct: "Sunday is my favorite day.", wrongs: ["Monday is my favorite day.", "I play soccer."] },
      { emoji: "💧", ja: "水曜日に体育がある", correct: "We have P.E. on Wednesday.", wrongs: ["We have P.E. on Thursday.", "I like red."] },
    ],
    fillblank: [
      { sentence: "Today is ___.", answer: "Monday", choices: ["Monday", "red", "dog", "rice"] },
      { sentence: "I have English on ___.", answer: "Friday", choices: ["Friday", "soccer", "milk", "cat"] },
      { sentence: "I like ___.", answer: "Saturday", choices: ["Saturday", "pencil", "blue", "bear"] },
      { sentence: "___ is my favorite day.", answer: "Sunday", choices: ["Sunday", "Apple", "Green", "Father"] },
      { sentence: "We have P.E. on ___.", answer: "Wednesday", choices: ["Wednesday", "baseball", "cake", "ear"] },
      { sentence: "Today is ___.", answer: "Thursday", choices: ["Thursday", "banana", "pink", "hand"] },
    ],
  },
  family: {
    reorder: [
      { parts: ["This", "is", "my", "mother", "."], answer: "This is my mother." },
      { parts: ["I", "love", "my", "family", "."], answer: "I love my family." },
      { parts: ["I", "have", "a", "brother", "."], answer: "I have a brother." },
      { parts: ["My", "father", "is", "kind", "."], answer: "My father is kind." },
      { parts: ["She", "is", "my", "sister", "."], answer: "She is my sister." },
      { parts: ["My", "grandmother", "is", "nice", "."], answer: "My grandmother is nice." },
    ],
    choose: [
      { emoji: "👩", ja: "これは私のお母さん", correct: "This is my mother.", wrongs: ["This is my sister.", "I like dogs."] },
      { emoji: "👨‍👩‍👧‍👦", ja: "家族が大好き", correct: "I love my family.", wrongs: ["I love my school.", "I play soccer."] },
      { emoji: "👦", ja: "兄弟がいる", correct: "I have a brother.", wrongs: ["I have a sister.", "I like red."] },
      { emoji: "👨", ja: "お父さんはやさしい", correct: "My father is kind.", wrongs: ["My father is big.", "I eat rice."] },
      { emoji: "👧", ja: "彼女は私の姉妹", correct: "She is my sister.", wrongs: ["She is my mother.", "I am ten."] },
      { emoji: "👵", ja: "おばあさんはやさしい", correct: "My grandmother is nice.", wrongs: ["My grandmother is tall.", "I like cake."] },
    ],
    fillblank: [
      { sentence: "This is my ___.", answer: "mother", choices: ["mother", "dog", "red", "Monday"] },
      { sentence: "I love my ___.", answer: "family", choices: ["family", "pencil", "blue", "soccer"] },
      { sentence: "I have a ___.", answer: "brother", choices: ["brother", "bird", "green", "cake"] },
      { sentence: "My ___ is kind.", answer: "father", choices: ["father", "cat", "yellow", "desk"] },
      { sentence: "She is my ___.", answer: "sister", choices: ["sister", "book", "pink", "Sunday"] },
      { sentence: "My ___ is nice.", answer: "grandmother", choices: ["grandmother", "apple", "white", "hand"] },
    ],
  },
};
