// 5年生レベル英単語データ
const WORD_DATA = {
  colors: {
    name: "いろ",
    icon: "🎨",
    words: [
      { en: "red", ja: "あか", emoji: "🔴" },
      { en: "blue", ja: "あお", emoji: "🔵" },
      { en: "green", ja: "みどり", emoji: "🟢" },
      { en: "yellow", ja: "きいろ", emoji: "🟡" },
      { en: "white", ja: "しろ", emoji: "⚪" },
      { en: "black", ja: "くろ", emoji: "⚫" },
      { en: "pink", ja: "ピンク", emoji: "🩷" },
      { en: "orange", ja: "オレンジ", emoji: "🟠" },
      { en: "purple", ja: "むらさき", emoji: "🟣" },
      { en: "brown", ja: "ちゃいろ", emoji: "🟤" },
    ],
  },
  numbers: {
    name: "すうじ",
    icon: "🔢",
    words: [
      { en: "one", ja: "1", emoji: "1️⃣" },
      { en: "two", ja: "2", emoji: "2️⃣" },
      { en: "three", ja: "3", emoji: "3️⃣" },
      { en: "four", ja: "4", emoji: "4️⃣" },
      { en: "five", ja: "5", emoji: "5️⃣" },
      { en: "six", ja: "6", emoji: "6️⃣" },
      { en: "seven", ja: "7", emoji: "7️⃣" },
      { en: "eight", ja: "8", emoji: "8️⃣" },
      { en: "nine", ja: "9", emoji: "9️⃣" },
      { en: "ten", ja: "10", emoji: "🔟" },
      { en: "eleven", ja: "11", emoji: "🔢" },
      { en: "twelve", ja: "12", emoji: "🔢" },
      { en: "twenty", ja: "20", emoji: "🔢" },
      { en: "hundred", ja: "100", emoji: "💯" },
    ],
  },
  animals: {
    name: "どうぶつ",
    icon: "🐾",
    words: [
      { en: "dog", ja: "いぬ", emoji: "🐕" },
      { en: "cat", ja: "ねこ", emoji: "🐈" },
      { en: "bird", ja: "とり", emoji: "🐦" },
      { en: "fish", ja: "さかな", emoji: "🐟" },
      { en: "rabbit", ja: "うさぎ", emoji: "🐰" },
      { en: "bear", ja: "くま", emoji: "🐻" },
      { en: "elephant", ja: "ぞう", emoji: "🐘" },
      { en: "lion", ja: "ライオン", emoji: "🦁" },
      { en: "monkey", ja: "さる", emoji: "🐵" },
      { en: "horse", ja: "うま", emoji: "🐴" },
      { en: "tiger", ja: "とら", emoji: "🐯" },
      { en: "snake", ja: "へび", emoji: "🐍" },
    ],
  },
  food: {
    name: "たべもの",
    icon: "🍽️",
    words: [
      { en: "rice", ja: "ごはん", emoji: "🍚" },
      { en: "bread", ja: "パン", emoji: "🍞" },
      { en: "egg", ja: "たまご", emoji: "🥚" },
      { en: "milk", ja: "ぎゅうにゅう", emoji: "🥛" },
      { en: "cake", ja: "ケーキ", emoji: "🎂" },
      { en: "pizza", ja: "ピザ", emoji: "🍕" },
      { en: "soup", ja: "スープ", emoji: "🍲" },
      { en: "salad", ja: "サラダ", emoji: "🥗" },
      { en: "meat", ja: "にく", emoji: "🥩" },
      { en: "fish", ja: "さかな", emoji: "🐟" },
      { en: "cheese", ja: "チーズ", emoji: "🧀" },
      { en: "candy", ja: "あめ", emoji: "🍬" },
    ],
  },
  fruits: {
    name: "くだもの",
    icon: "🍎",
    words: [
      { en: "apple", ja: "りんご", emoji: "🍎" },
      { en: "banana", ja: "バナナ", emoji: "🍌" },
      { en: "orange", ja: "オレンジ", emoji: "🍊" },
      { en: "grape", ja: "ぶどう", emoji: "🍇" },
      { en: "strawberry", ja: "いちご", emoji: "🍓" },
      { en: "peach", ja: "もも", emoji: "🍑" },
      { en: "cherry", ja: "さくらんぼ", emoji: "🍒" },
      { en: "lemon", ja: "レモン", emoji: "🍋" },
      { en: "watermelon", ja: "すいか", emoji: "🍉" },
      { en: "melon", ja: "メロン", emoji: "🍈" },
    ],
  },
  body: {
    name: "からだ",
    icon: "🫀",
    words: [
      { en: "head", ja: "あたま", emoji: "🗣️" },
      { en: "eye", ja: "め", emoji: "👁️" },
      { en: "ear", ja: "みみ", emoji: "👂" },
      { en: "nose", ja: "はな", emoji: "👃" },
      { en: "mouth", ja: "くち", emoji: "👄" },
      { en: "hand", ja: "て", emoji: "✋" },
      { en: "foot", ja: "あし", emoji: "🦶" },
      { en: "arm", ja: "うで", emoji: "💪" },
      { en: "leg", ja: "あし（きゃく）", emoji: "🦵" },
      { en: "face", ja: "かお", emoji: "😊" },
    ],
  },
  school: {
    name: "がっこう",
    icon: "🏫",
    words: [
      { en: "book", ja: "ほん", emoji: "📖" },
      { en: "pen", ja: "ペン", emoji: "🖊️" },
      { en: "desk", ja: "つくえ", emoji: "🪑" },
      { en: "chair", ja: "いす", emoji: "💺" },
      { en: "bag", ja: "かばん", emoji: "🎒" },
      { en: "ruler", ja: "ものさし", emoji: "📏" },
      { en: "eraser", ja: "けしゴム", emoji: "🧽" },
      { en: "pencil", ja: "えんぴつ", emoji: "✏️" },
      { en: "notebook", ja: "ノート", emoji: "📓" },
      { en: "teacher", ja: "せんせい", emoji: "👩‍🏫" },
      { en: "student", ja: "せいと", emoji: "🧑‍🎓" },
      { en: "school", ja: "がっこう", emoji: "🏫" },
    ],
  },
  sports: {
    name: "スポーツ",
    icon: "⚽",
    words: [
      { en: "soccer", ja: "サッカー", emoji: "⚽" },
      { en: "baseball", ja: "やきゅう", emoji: "⚾" },
      { en: "basketball", ja: "バスケ", emoji: "🏀" },
      { en: "tennis", ja: "テニス", emoji: "🎾" },
      { en: "swimming", ja: "すいえい", emoji: "🏊" },
      { en: "running", ja: "はしること", emoji: "🏃" },
      { en: "volleyball", ja: "バレーボール", emoji: "🏐" },
      { en: "badminton", ja: "バドミントン", emoji: "🏸" },
      { en: "skiing", ja: "スキー", emoji: "⛷️" },
      { en: "skating", ja: "スケート", emoji: "⛸️" },
    ],
  },
  days: {
    name: "ようび",
    icon: "📅",
    words: [
      { en: "Sunday", ja: "にちようび", emoji: "☀️" },
      { en: "Monday", ja: "げつようび", emoji: "🌙" },
      { en: "Tuesday", ja: "かようび", emoji: "🔥" },
      { en: "Wednesday", ja: "すいようび", emoji: "💧" },
      { en: "Thursday", ja: "もくようび", emoji: "🌳" },
      { en: "Friday", ja: "きんようび", emoji: "✨" },
      { en: "Saturday", ja: "どようび", emoji: "🌍" },
    ],
  },
  family: {
    name: "かぞく",
    icon: "👨‍👩‍👧‍👦",
    words: [
      { en: "father", ja: "おとうさん", emoji: "👨" },
      { en: "mother", ja: "おかあさん", emoji: "👩" },
      { en: "brother", ja: "きょうだい（おとこ）", emoji: "👦" },
      { en: "sister", ja: "きょうだい（おんな）", emoji: "👧" },
      { en: "baby", ja: "あかちゃん", emoji: "👶" },
      { en: "friend", ja: "ともだち", emoji: "🤝" },
      { en: "family", ja: "かぞく", emoji: "👨‍👩‍👧‍👦" },
      { en: "grandfather", ja: "おじいさん", emoji: "👴" },
      { en: "grandmother", ja: "おばあさん", emoji: "👵" },
    ],
  },
};
