// 5年生レベル英単語データ
// confusables: 紛らわしい偽選択肢
// tip: 覚え方ヒント
const WORD_DATA = {
  colors: {
    name: "いろ",
    icon: "🎨",
    words: [
      { en: "red", ja: "赤", emoji: "🔴", confusables: ["rod", "rid", "rad"], tip: "「レッド」→ red。eが1つだけ！" },
      { en: "blue", ja: "青", emoji: "🔵", confusables: ["blur", "bleu", "bule"], tip: "bl + ue。「ブルー」をそのままローマ字にしないでね！" },
      { en: "green", ja: "緑", emoji: "🟢", confusables: ["grean", "gleen", "griin"], tip: "gr + een。eが2つ並ぶよ！" },
      { en: "yellow", ja: "黄色", emoji: "🟡", confusables: ["yello", "yerrow", "yellou"], tip: "yell（さけぶ）+ ow。さけぶほど明るい色！" },
      { en: "white", ja: "白", emoji: "⚪", confusables: ["wite", "whyte", "whit"], tip: "wh + ite。hを忘れないで！" },
      { en: "black", ja: "黒", emoji: "⚫", confusables: ["blak", "brack", "bluck"], tip: "bl + ack。「ブラック」のまま！" },
      { en: "pink", ja: "ピンク", emoji: "🩷", confusables: ["pnk", "pinc", "penk"], tip: "p + ink（インク）。ピンクのインク！" },
      { en: "orange", ja: "オレンジ", emoji: "🟠", confusables: ["orenge", "oranye", "olange"], tip: "or + ange。果物のオレンジと同じスペル！" },
      { en: "purple", ja: "紫", emoji: "🟣", confusables: ["purpel", "puple", "parple"], tip: "pur + ple。rを忘れないで！" },
      { en: "brown", ja: "茶色", emoji: "🟤", confusables: ["blown", "broun", "btown"], tip: "br + own（自分の）。自分の色＝茶色！" },
    ],
  },
  numbers: {
    name: "数字",
    icon: "🔢",
    words: [
      { en: "one", ja: "1", emoji: "1️⃣", confusables: ["won", "oun", "ane"], tip: "won（勝った）と同じ発音だけどスペルが違う！" },
      { en: "two", ja: "2", emoji: "2️⃣", confusables: ["too", "tow", "tue"], tip: "too（〜も）と同じ発音！wがポイント！" },
      { en: "three", ja: "3", emoji: "3️⃣", confusables: ["thre", "tree", "threa"], tip: "tree（木）にhを足すと three！" },
      { en: "four", ja: "4", emoji: "4️⃣", confusables: ["for", "fore", "foor"], tip: "for（〜のために）にuを足すと four！" },
      { en: "five", ja: "5", emoji: "5️⃣", confusables: ["fiv", "fibe", "hive"], tip: "f + ive。hive（ハチの巣）と似てるから注意！" },
      { en: "six", ja: "6", emoji: "6️⃣", confusables: ["siz", "sicks", "sox"], tip: "3文字だけ！シンプル！" },
      { en: "seven", ja: "7", emoji: "7️⃣", confusables: ["saven", "sevan", "sevn"], tip: "se + ven。「セブン」そのまま！" },
      { en: "eight", ja: "8", emoji: "8️⃣", confusables: ["eigt", "aight", "eigth"], tip: "eightのghは読まない！8は特別なスペル！" },
      { en: "nine", ja: "9", emoji: "9️⃣", confusables: ["nein", "nain", "nin"], tip: "n + ine。line（線）と同じine！" },
      { en: "ten", ja: "10", emoji: "🔟", confusables: ["tin", "tan", "tne"], tip: "3文字！pen（ペン）と同じパターン！" },
      { en: "eleven", ja: "11", emoji: "🔢", confusables: ["elaven", "elevan", "elevel"], tip: "e + leven。eで始まってeで終わる！" },
      { en: "twelve", ja: "12", emoji: "🔢", confusables: ["twelv", "twelf", "twleve"], tip: "twel + ve。veで終わる！" },
      { en: "twenty", ja: "20", emoji: "🔢", confusables: ["twanty", "tweny", "twinty"], tip: "twen + ty。twin（ふたご）に似てる！2の十！" },
      { en: "hundred", ja: "100", emoji: "💯", confusables: ["hunderd", "hundled", "handred"], tip: "hun + dred。「ハンドレッド」dが2つ！" },
    ],
  },
  animals: {
    name: "動物",
    icon: "🐾",
    words: [
      { en: "dog", ja: "犬", emoji: "🐕", confusables: ["dob", "dag", "doog"], tip: "3文字！god（神）を逆さにすると dog！" },
      { en: "cat", ja: "猫", emoji: "🐈", confusables: ["kat", "cot", "cut"], tip: "3文字！bat（コウモリ）と同じパターン！" },
      { en: "bird", ja: "鳥", emoji: "🐦", confusables: ["brid", "bard", "bied"], tip: "bir + d。「バード」のirを忘れないで！" },
      { en: "fish", ja: "魚", emoji: "🐟", confusables: ["fich", "fesh", "fysb"], tip: "f + ish（〜っぽい）。shで終わる！" },
      { en: "rabbit", ja: "うさぎ", emoji: "🐰", confusables: ["rabit", "rabitt", "rabbid"], tip: "rab + bit。bが2つ！tは1つ！" },
      { en: "bear", ja: "熊", emoji: "🐻", confusables: ["beer", "bere", "bare"], tip: "bear。ear（耳）が入ってる！熊の耳！" },
      { en: "elephant", ja: "象", emoji: "🐘", confusables: ["elefant", "elephunt", "eliphant"], tip: "ele + phant。phで「フ」の音！" },
      { en: "lion", ja: "ライオン", emoji: "🦁", confusables: ["rion", "loin", "leon"], tip: "li + on。「ライオン」のまま！lで始まる！" },
      { en: "monkey", ja: "猿", emoji: "🐵", confusables: ["monky", "mankey", "munkey"], tip: "mon + key（かぎ）。猿がカギを持ってる！" },
      { en: "horse", ja: "馬", emoji: "🐴", confusables: ["hores", "hoese", "hourse"], tip: "hor + se。「ホース」に似てるけどuはない！" },
      { en: "tiger", ja: "虎", emoji: "🐯", confusables: ["tager", "teger", "tigar"], tip: "ti + ger。「タイガー」のまま！" },
      { en: "snake", ja: "蛇", emoji: "🐍", confusables: ["sneke", "snaik", "snace"], tip: "sn + ake（〜のように）。cake, lakeと同じパターン！" },
    ],
  },
  food: {
    name: "食べ物",
    icon: "🍽️",
    words: [
      { en: "rice", ja: "ごはん", emoji: "🍚", confusables: ["rise", "ries", "lice"], tip: "r + ice（こおり）。氷の上のごはん？！" },
      { en: "bread", ja: "パン", emoji: "🍞", confusables: ["blead", "breid", "breed"], tip: "bre + ad。read（読む）にbをつけるとパン！" },
      { en: "egg", ja: "卵", emoji: "🥚", confusables: ["eeg", "eggu", "agg"], tip: "3文字！gが2つ並ぶ！" },
      { en: "milk", ja: "牛乳", emoji: "🥛", confusables: ["mirk", "mlik", "milc"], tip: "mil + k。「ミルク」そのまま！" },
      { en: "cake", ja: "ケーキ", emoji: "🎂", confusables: ["caik", "ceke", "kake"], tip: "c + ake。lake, makeと同じパターン！" },
      { en: "pizza", ja: "ピザ", emoji: "🍕", confusables: ["piza", "pixa", "pezza"], tip: "piz + za。zが2つ！" },
      { en: "soup", ja: "スープ", emoji: "🍲", confusables: ["soop", "sup", "soupe"], tip: "s + oup。group（グループ）にもoupが入ってる！" },
      { en: "salad", ja: "サラダ", emoji: "🥗", confusables: ["sarad", "saled", "salld"], tip: "sal + ad。「サラダ」のlとrに注意！" },
      { en: "meat", ja: "肉", emoji: "🥩", confusables: ["meet", "meit", "miet"], tip: "m + eat（食べる）。肉を食べる＝meat！" },
      { en: "cheese", ja: "チーズ", emoji: "🧀", confusables: ["cheeze", "chees", "chiise"], tip: "chee + se。eが3つもある！" },
      { en: "candy", ja: "あめ", emoji: "🍬", confusables: ["candie", "kandy", "cundy"], tip: "can + dy。can（できる）＋dy！" },
    ],
  },
  fruits: {
    name: "果物",
    icon: "🍎",
    words: [
      { en: "apple", ja: "りんご", emoji: "🍎", confusables: ["aple", "appel", "aplle"], tip: "ap + ple。pが2つ！" },
      { en: "banana", ja: "バナナ", emoji: "🍌", confusables: ["banane", "bannana", "benana"], tip: "ba + na + na。naが2回！" },
      { en: "orange", ja: "オレンジ", emoji: "🍊", confusables: ["olange", "oranye", "orenge"], tip: "or + ange。色のorangeと同じ！" },
      { en: "grape", ja: "ぶどう", emoji: "🍇", confusables: ["glape", "graps", "grepe"], tip: "gr + ape（サル）。サルがぶどうを食べてる！" },
      { en: "strawberry", ja: "いちご", emoji: "🍓", confusables: ["strawbery", "strowberry", "strawbelry"], tip: "straw（ストロー）+ berry（ベリー）。2つの単語の合体！" },
      { en: "peach", ja: "桃", emoji: "🍑", confusables: ["peech", "pech", "peatch"], tip: "p + each（それぞれ）。eachがそのまま入ってる！" },
      { en: "cherry", ja: "さくらんぼ", emoji: "🍒", confusables: ["chery", "chelry", "charry"], tip: "cher + ry。rが2つ！" },
      { en: "lemon", ja: "レモン", emoji: "🍋", confusables: ["limon", "lemmon", "remon"], tip: "le + mon。「レモン」そのまま！lで始まる！" },
      { en: "watermelon", ja: "すいか", emoji: "🍉", confusables: ["wetermelon", "watermellon", "watermelan"], tip: "water（水）+ melon（メロン）。水っぽいメロン！" },
      { en: "melon", ja: "メロン", emoji: "🍈", confusables: ["mellon", "meron", "melan"], tip: "me + lon。lが1つだけ！" },
    ],
  },
  body: {
    name: "体",
    icon: "🫀",
    words: [
      { en: "head", ja: "頭", emoji: "🗣️", confusables: ["hed", "heed", "hade"], tip: "h + ead。read（読む）と同じeadパターン！" },
      { en: "eye", ja: "目", emoji: "👁️", confusables: ["eya", "aye", "eey"], tip: "3文字！yが真ん中！見た目も目みたい？" },
      { en: "ear", ja: "耳", emoji: "👂", confusables: ["eer", "ier", "aer"], tip: "3文字！ear。hear（聞く）にも入ってる！" },
      { en: "nose", ja: "鼻", emoji: "👃", confusables: ["noze", "noes", "noce"], tip: "no + se。rose（バラ）と似てる！" },
      { en: "mouth", ja: "口", emoji: "👄", confusables: ["mowth", "moath", "mauth"], tip: "m + outh。south（南）と同じouth！" },
      { en: "hand", ja: "手", emoji: "✋", confusables: ["hend", "hund", "hant"], tip: "h + and（そして）。handの中にandがある！" },
      { en: "foot", ja: "足", emoji: "🦶", confusables: ["fut", "foos", "feat"], tip: "f + oot。oが2つ！book, cookと同じパターン！" },
      { en: "arm", ja: "腕", emoji: "💪", confusables: ["aam", "alm", "aem"], tip: "3文字！farm（農場）からfを取るとarm！" },
      { en: "leg", ja: "脚", emoji: "🦵", confusables: ["leg", "reg", "lag"], tip: "3文字！egg（卵）と似てるけどlで始まる！" },
      { en: "face", ja: "顔", emoji: "😊", confusables: ["fece", "fase", "faice"], tip: "f + ace（エース）。顔はエース！" },
    ],
  },
  school: {
    name: "学校",
    icon: "🏫",
    words: [
      { en: "book", ja: "本", emoji: "📖", confusables: ["bouk", "boak", "bock"], tip: "b + ook。cook（料理する）look（見る）と同じパターン！" },
      { en: "pen", ja: "ペン", emoji: "🖊️", confusables: ["pan", "pin", "pne"], tip: "3文字！ten（10）と同じパターン！" },
      { en: "desk", ja: "机", emoji: "🪑", confusables: ["dask", "disc", "desck"], tip: "des + k。「デスク」そのまま！" },
      { en: "chair", ja: "椅子", emoji: "💺", confusables: ["cheer", "chiar", "cher"], tip: "ch + air（空気）。空気の椅子！" },
      { en: "bag", ja: "かばん", emoji: "🎒", confusables: ["beg", "bug", "baq"], tip: "3文字！big（大きい）と似てるけど真ん中はa！" },
      { en: "ruler", ja: "ものさし", emoji: "📏", confusables: ["ruller", "rular", "luler"], tip: "rule（ルール）+ r。ルールを引く道具！" },
      { en: "eraser", ja: "消しゴム", emoji: "🧽", confusables: ["erazar", "erasar", "elaser"], tip: "erase（消す）+ r。消す人＝消しゴム！" },
      { en: "pencil", ja: "えんぴつ", emoji: "✏️", confusables: ["pensil", "pencle", "pencel"], tip: "pen + cil。ペンの仲間！" },
      { en: "notebook", ja: "ノート", emoji: "📓", confusables: ["notbook", "noatbook", "notebock"], tip: "note（メモ）+ book（本）。メモの本！" },
      { en: "teacher", ja: "先生", emoji: "👩‍🏫", confusables: ["techer", "teecher", "teachar"], tip: "teach（教える）+ er（人）。教える人！" },
      { en: "student", ja: "生徒", emoji: "🧑‍🎓", confusables: ["studant", "studdent", "stundent"], tip: "stud + ent。study（勉強する）の仲間！" },
      { en: "school", ja: "学校", emoji: "🏫", confusables: ["skool", "shool", "scool"], tip: "sch + ool。chで「ク」の音！cool（かっこいい）に似てる！" },
    ],
  },
  sports: {
    name: "スポーツ",
    icon: "⚽",
    words: [
      { en: "soccer", ja: "サッカー", emoji: "⚽", confusables: ["socer", "soccor", "soccar"], tip: "soc + cer。cが2つ！" },
      { en: "baseball", ja: "野球", emoji: "⚾", confusables: ["basball", "baisball", "baseboll"], tip: "base（ベース）+ ball（ボール）。塁のボール！" },
      { en: "basketball", ja: "バスケ", emoji: "🏀", confusables: ["baskelball", "basketbal", "bascetball"], tip: "basket（かご）+ ball。かごにボールを入れる！" },
      { en: "tennis", ja: "テニス", emoji: "🎾", confusables: ["tenis", "teniss", "tennes"], tip: "ten + nis。nが2つ！" },
      { en: "swimming", ja: "水泳", emoji: "🏊", confusables: ["swiming", "swiminng", "swimmeng"], tip: "swim + ming。mが2つ！" },
      { en: "running", ja: "走ること", emoji: "🏃", confusables: ["runing", "runneng", "ranning"], tip: "run + ning。nが2つ！" },
      { en: "volleyball", ja: "バレーボール", emoji: "🏐", confusables: ["voleyball", "valleyball", "vollyball"], tip: "volley + ball。lが2つ！" },
      { en: "badminton", ja: "バドミントン", emoji: "🏸", confusables: ["badminten", "badmington", "batminton"], tip: "bad + min + ton。「バドミントン」そのまま！最後にgはない！" },
      { en: "skiing", ja: "スキー", emoji: "⛷️", confusables: ["skeing", "skieng", "skiiing"], tip: "ski + ing。iが2つ並ぶ！" },
      { en: "skating", ja: "スケート", emoji: "⛸️", confusables: ["skateing", "skaiting", "sketing"], tip: "skate - e + ing。eを取ってingをつける！" },
    ],
  },
  days: {
    name: "曜日",
    icon: "📅",
    words: [
      { en: "Sunday", ja: "日曜日", emoji: "☀️", confusables: ["Sanday", "Sundey", "Sundy"], tip: "Sun（太陽）+ day（日）。太陽の日！" },
      { en: "Monday", ja: "月曜日", emoji: "🌙", confusables: ["Munday", "Mondey", "Mondy"], tip: "Mon（Moon=月）+ day。月の日！" },
      { en: "Tuesday", ja: "火曜日", emoji: "🔥", confusables: ["Tuseday", "Teusday", "Tueday"], tip: "Tues + day。「チューズデイ」sを忘れないで！" },
      { en: "Wednesday", ja: "水曜日", emoji: "💧", confusables: ["Wendsday", "Wednsday", "Wensday"], tip: "Wed + nes + day。dの後のneを忘れないで！" },
      { en: "Thursday", ja: "木曜日", emoji: "🌳", confusables: ["Thersday", "Thirsday", "Thurday"], tip: "Thurs + day。「サーズデイ」rsを忘れないで！" },
      { en: "Friday", ja: "金曜日", emoji: "✨", confusables: ["Fryday", "Frieday", "Friady"], tip: "Fri + day。fry（揚げる）と同じ発音だけどiが違う！" },
      { en: "Saturday", ja: "土曜日", emoji: "🌍", confusables: ["Saterday", "Satarday", "Saturdy"], tip: "Satur + day。「サタデー」urを忘れないで！" },
    ],
  },
  family: {
    name: "家族",
    icon: "👨‍👩‍👧‍👦",
    words: [
      { en: "father", ja: "お父さん", emoji: "👨", confusables: ["farther", "fater", "fathar"], tip: "fa + ther。「ファーザー」thの音！" },
      { en: "mother", ja: "お母さん", emoji: "👩", confusables: ["mouther", "mather", "moter"], tip: "mo + ther。fatherと同じther！" },
      { en: "brother", ja: "兄弟", emoji: "👦", confusables: ["brather", "bruther", "blother"], tip: "bro + ther。mother, fatherと同じther！" },
      { en: "sister", ja: "姉妹", emoji: "👧", confusables: ["sster", "sistar", "cister"], tip: "sis + ter。「シスター」そのまま！" },
      { en: "baby", ja: "赤ちゃん", emoji: "👶", confusables: ["beby", "babie", "babe"], tip: "ba + by。「ベイビー」byで終わる！" },
      { en: "friend", ja: "友達", emoji: "🤝", confusables: ["frend", "freind", "fiend"], tip: "fri + end（終わり）。終わらない友情！iの位置に注意！" },
      { en: "family", ja: "家族", emoji: "👨‍👩‍👧‍👦", confusables: ["famiry", "famaly", "famliy"], tip: "fam + i + ly。「ファミリー」lとrに注意！" },
      { en: "grandfather", ja: "おじいさん", emoji: "👴", confusables: ["granfather", "grandfarther", "grandfater"], tip: "grand（偉大な）+ father。偉大なお父さん！" },
      { en: "grandmother", ja: "おばあさん", emoji: "👵", confusables: ["granmother", "grandmather", "grandmoter"], tip: "grand（偉大な）+ mother。偉大なお母さん！" },
    ],
  },
};
